#!/bin/sh

echo "\n\n** PRE-COMMIT => Regenerating schema.graphql"
npm run fetch-schema
git add schema.graphql

echo "\n\n** PRE-COMMIT => Pre Compiling Relay"
npm run relay

echo "\n\n** PRE-COMMIT => Fix Stylelint"
npm run fix:stylelint

echo "\n\n** PRE-COMMIT => Fix ESLint"
npm run fix:eslint

exit 0
